разметка
htmlacademy-htmlcss/1804799-device-31 pull request #2
Opened 2021-05-23 15:26 UTC by Debi7

2021-05-23 21:39 UTC, wrgraff requested changes
Картинки не надо было экспортировать: формат не тот.
А зачем js-файлы тебе сейчас?

Каталог пока не смотрел, возможно ты в нем что-то поправишь после ревью главной.
Но на будущее лучше 2 задания в одно не ставь.

Немного о том, как я ревью делаю.
Важные моменты, на которые нужно обязательно обратить внимание, я отмечаю смайлом ракеты 🚀. То, что в правках не нуждается, отмечено смайлом 👍. Некоторые комментарии без отметок. Если не понимаешь их или не успеваешь, то можно их оставить до следующей консультации или же вообще пропустить.
Еще прошу не нажимать на кнопку "Resolve conversation". Мне потом неудобно смотреть что я там написал. Пускай это будет моя кнопка =) Я буду ее жать если проблема исправлена. Ты можешь для себя тоже отмечать исправленный комментарий каким-то эмодзи, или писать комментарий в ответ. Как захочешь.

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +        <a href="catalog.html"><img src="icons/cross.png" alt="каталог">Каталог товаров</a>
Выпадающее подменю должно быть где-то рядом со ссылкой на каталог товаров:
![изображение](https://user-images.githubusercontent.com/37917037/119276529-5b812680-bc23-11eb-9512-3875ba8a2c78.png)

А у тебя оно где-то в отрыве совсем

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +      </figure>
Почему обернула в ссылку? Я не видел, что с картинки ссылка должна быть.

`figure` здесь несколько излишен. Он хорош для картинок, которые хочется подписать. Какой-нибудь график внутри статьи или другая иллюстрация очень бы хорошо подошли.

А тут... Просто картинка для слайдера.

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +      <h2>Порхает как бабочка, <br> жалит как пчела!</h2>
Заголовок должен описывать контент. Вот как "Популярные товары" ниже (хотя там скорее разделы, да и они представлены все, а не только популярные). Но все равно, в плане характерного описания это больше заголовок.
Этот текст на заголовок не похож. Он ничего не проясняет в плане содержания. Это просто слоган.

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +      <p>Этот обычный, на первый взгляд, квадрокоптер оснащен <br>
Давай договоримся пока не использовать `<br>.`
Дело в том, что форматированный текст вести себя будет иначе, а нам на этапе сеток нужно будет убедиться, что он подстраивается под сетку вне зависимости от форматирования.
Мы потом сможем поставить переносы, если это будет нужно.

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +      </ul>
Там 3 слайда.
Надо разметить все 3.
А вот эти элементы управления — одни и те же для них. так что они в слайде быть не должны.

Типа такого:

- Слайдер
  - Слайды
    - Слайд
    - Слайд
    - Слайд
  - Кнопки управления

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +        <p>Дальность полета</p>
`<p>` нельзя вкладывать в `<ul>`.

Подумай, какой другой набор тегов хорошо подойдет для формата данных типа "ключ-значение"?

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +      <section>
Вообще, по хорошему, если ты создаешь `<section>`, то в нем должен быть какой-то контент, который можно озаглавить.
Валидатор даже требует наличия заголовка в теге `<section>`. Там это не ошибка, но предупреждение.

То есть, на самом деле, это правило даже должно помочь распределять на секции контент. Если можешь озаглавить, значит можно выделить в `<section>`.
Если не получается — лучше не стоит.

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +      <h2>Популярные товары</h2>
Заголовки — они как дерево. h1 как ствол дерева, а все прочие растут от него. И каждый заголовок вырастает из другого заголовка:

- h1
  - h2
    - h3
    - h3
  - h2
  - h2
  - h2
    - h3
      - h4
      - h4
      
А у тебя получается что второй уровень есть, а первого нет еще

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +        </li>
Отсутствие alt у картинки — первый признак того, что она не нужна в разметке.
Если ее нельзя описать или описание будет повторять текстовую подпись, то картинка в разметке не очень полезна и можно сделать ее декоративной через стили.

Ну и тем более не стоит вешать ссылку на картинку. Повесить надо на заголовок ее.

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +      <img src="icons/" alt="человечек">
Зачем он тут )

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +      </ul>
Это не просто список, это интерактивные элементы, своеобразные такие вкладки.
Сделай их так, чтобы можно было с ними взаимодействовать

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +    </section>
В этой секции не только доставка, там 3 блока.
Еще есть гарантия и кредит. Их тоже разметить надо

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +      <h2>Логотипы</h2>
Какие логотипы?
Зачем? Почему? Чьи?

Судя по названием — это бренды, которые продаются на сайте. Или партнеры какие-то.
Точно мы не знаем, а уточнить не у кого.
Поэтому кто это решай сама, но только не просто "логотипы" =)

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +            <img src="img/logo-1.png" width="260" height="100" alt="">
Обязательно впиши alt.
Тут это даже не сложно, какая картинка изображена, тот бренд и вписать

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +    <!--страница Каталог-->
Нет, страница каталог тут не нужна ))

2021-05-23 21:39 UTC, wrgraff commented on index.html
> +    </section>
Как-то запутанно объеденено по секциям.
Перепроверить надо логику. Попробуй подобрать к секциям заголовки

2021-05-24 14:46 UTC, Debi7 commented on index.html
> +          <li><a href="blank.html"><img class="compare__img" src="icons/compare.png" alt="сравнить">Сравнить</a></li>
ок, пока без БЭМ

2021-05-25 12:53 UTC, Debi7 commented
сделала правки.

2021-05-25 22:02 UTC, wrgraff commented on index.html
> +  <header class="header">
Все равно не понимаю я твою систему именований.
Ну ладно, лайв по ним будет — еще сама захочешь переписать, вот увидишь.

2021-05-25 22:05 UTC, wrgraff commented on index.html
> +        <button type="submit">НАЙТИ</button>
Только не пиши капсом, пиши как обычно "Найти".
Остальное через стили

2021-05-25 22:05 UTC, wrgraff commented on index.html
> +        <label for="field-search"></label>
Так, а мы ж обсуждали-обсуждали с тобой, что обязательно в лейбле текст нужен.
Поставь уж текст то

2021-05-25 22:06 UTC, wrgraff commented on index.html
> +          <li><a href="blank.html"><img class="compare__img" src="icons/compare.png" alt="сравнить">Сравнить</a></li>
Понял, принял

2021-05-25 22:09 UTC, wrgraff commented on index.html
> +          </li>
Красиво

2021-05-25 22:09 UTC, wrgraff commented on index.html
> +      </ul>
Не разметила 3 слайда пока что.
И вообще, мне кажется, ты в нем подзапуталась. Может, созвониться нам по нему завтра?

2021-05-25 22:11 UTC, wrgraff commented on index.html
> +      </dl>
Супер, правильно подобрала, молодец

2021-05-25 22:11 UTC, wrgraff commented on index.html
> +      </ul>
Теперь эти элементы пропали.
Там эта часть состоит из двух основных элементов: вкладки и контент вкладок.

2021-05-25 23:04 UTC, wrgraff requested changes
Молодец, это хорошая работа. Но надо еще править.
Страницу каталога тоже проверил.

2021-05-25 23:04 UTC, wrgraff commented on catalog.html
> +            1 100 руб.
Насколько я вижу, скорее заголовок объединен с ценой.
А у тебя какая-то такая структура:
![изображение](https://user-images.githubusercontent.com/37917037/119578970-282acd00-bdc6-11eb-8b07-4986566e878e.png)

Зачем? Не мудри. Сделай проще:
Картинка, за ней заголовок и цена, отдельно — кнопки/ссылки.

И на тему того, где должна быть ссылка. Внимательно [читаем ТЗ](https://up.htmlacademy.ru/htmlcss/31/project/device#device-3-15)!

2021-05-25 23:04 UTC, wrgraff commented on catalog.html
> +            <!---->
А это что?

2021-05-25 23:04 UTC, wrgraff commented on catalog.html
> +      <ul>
Почему каждый товар в списке?
У тебя тут... Какой-то список списков ) Из одного пункта.

2021-05-25 23:04 UTC, wrgraff commented on catalog.html
> +      <section>
Тоже заголовок бы, если выделяешь в секцию

2021-05-26 22:55 UTC, wrgraff requested changes
Есть несколько всего критичных моментов.
Но особенно меня беспокоит беспорядок с заголовками и структурой. У тебя должна получиться красивая логичная структура документа.

Записал [небольшой скринкаст](https://youtu.be/lvfg6RLNINQ) на быструю руку о том, как соотносятся в разметке заголовки и секции.
Надеюсь, поможет в составлении структуры.
Еще можно [генератором HTML-дерева](https://yoksel.github.io/html-tree/) пользоваться чтобы увидеть какие заголовки на странице.

2021-05-29 13:12 UTC, wrgraff requested changes
Пара важных комментов и немного лирики

2021-05-29 13:12 UTC, wrgraff commented on index.html
> +      </li>
Немного UX: на кнопках стоит писать действие, в формате глагола.
"Показать слайд с квадрокоптером" — как-то так

2021-05-29 13:12 UTC, wrgraff commented on index.html
> +    <h1>Контент главной страницы сайта</h1>
Обычно на главной сборная солянка про весь сайт, а заголовок по сути весь сайт и описывает.
"Магазин гаджетов Device"

2021-05-29 13:12 UTC, wrgraff commented on index.html
> +            <img src="icons/brand-4.svg" width="260" height="100" alt="VIVE">
Они ж все растровые =)
Обрати внимание на иконки рядом с лого:
![изображение](https://user-images.githubusercontent.com/37917037/120071363-9b1e9700-c097-11eb-9aa3-887ab62a327b.png)

Растр вектором делать не надо. Там просто растровая картинка заворачивается в `<svg>...</svg>`. И она очень плохо сжимается.
Разве что ты найдешь векторные исходники этих логотипов (потому что в целом конечно вектор круче)

2021-05-29 13:12 UTC, wrgraff commented on index.html
> +      <img src="img/map.svg" width="560" height="222" alt="карта">
Карта похожа немного на вектор, но Яндекс и Гугл экспортируют их обычно растром.
Вектор тут был бы довольно сложный и весил бы много скорее всего.

2021-05-29 13:12 UTC, wrgraff commented on index.html
> +    <img src="img/map-big.svg" width="960" height="572" alt="карта">
Но тут уже не вопрос оптимизации. У нас доступ есть только к растровой графике

2021-05-31 19:49 UTC, wrgraff requested changes
Ну вот, опять целое ревью.
А так хотелось графику принять... Эх

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +            <a class="basket-link" href="blank.html">Корзина</a>
Вот эти ссылки выглядят почти одинаково.
Иконки только разные. Можно им дать класс, который будет давать все общие для них стили.
И еще один класс, который будет добавлять только иконку.

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +        <ul class="conditions">
А почему `conditions`?

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +    <section class="form">
`form` — плохой класс для этого блока.
Если это форма, то что такое форма обратной связи? Форма заказа?

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +          <legend class="range-p">Стоимость</legend>
Что значит `range-p`?
Вот я например понятия не имею что это за "пи". А нейминг должен быть таким, чтобы очевидно было

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +        <fieldset class="filter-color">
Вот почему у тебя цвет `filter-color`, а диапазон просто `range`, а не `filter-range`?

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +            <li class="color-item">
Как ты думаешь, если бы этот чекбокс был бы о чем угодно другом, а не о цвете: он бы выглядел как-то иначе?
Другими словами: Не нужно ли как-то выделить ему еще один класс, который будет отдельно задавать стили чекбокса без учета того, в каком он контексте?

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +          <ul class="bluetooth-list">
В прицнипе, кроме чекбоксов, можно и про филдсеты спросить тоже самое.
Чем визуально список про блютус отличается от списка про цвет?

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +      <a class="arrowDown" href="#"><img src="icons/arrow_down.svg" alt="стрелка вниз"></a>
Это с чего вдруг у нас запись из `kebab-case` превратилась в `camelCase`?

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +          <img class="stick1" src="img/stick_tel.jpg" width="360" height="380" alt="Любительская селфи-палка">
Моим студентам нельзя использовать классы типа `something-1`, `something-2`, и так далее.

Если тебе нужно стилизовать что-то по порядковому номеру, то в CSS есть такие вещи, как `:first-child`, `:nth-child`, `:nth-of-type` и прочие. Они придуманы специально чтобы выбирать элемент по порядку. И если их в разметке перемешать, то они все равно будут выбирать по порядку.

Если же необходимо дать стили элементу так, чтобы при перемешивании стили оставались при нём (например, иконка, которая относится непосредственно к элементу), то нужен класс.
Но только не с именем "первый", потому что оформление зависит от того, что это за элемент, а не какой он по порядку.

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +          <p class="stick1-p">
Зачем тебе вообще разные классы на этих тегах?
Они оформлены одинаково.

А если ты их оставишь, то бэкендер как понимать будет что за класс там нужен?

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +          <a class="btn-basket" href="#">В корзину</a>
Кажется, эта кнопка от многих других кнопок не отличается.
Ей точно нужен полностью отдельный класс?

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +      <a class="button-next" href="#">вперед</a>
А вперед от назад чем отличается?

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +          <a class="social-btn" href="#"><img src="icons/icon_witter.svg" alt="Вконтакте">Вконтакте</a>
Зачем иконку в контент засунула?

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +          <a href="blank.html">Контакты</a>
А вот тут как раз вопрос насколько этот блок похож на блок в хэдере.
Когда расставляешь классы, нужно вообще иметь ввиду, что они нужны для оформления, а не задания смысла.
У тебя могут быть как разные теги с одинаковыми классами (самое частое — это кнопка и ссылка, которые выглядят одинаково) и очень схожие по смыслу элементы с разными классами, так как выглядят они совершенно по разному (да хоть то же меню часто в хэдере и футере из общего имеют только состав).

2021-05-31 19:49 UTC, wrgraff commented on catalog.html
> +      <a class="btn" href="https://htmlacademy.ru">HTML Academy</a>
А этим двум элементам одинаковые классы задала:
![изображение](https://user-images.githubusercontent.com/37917037/120234711-34e57000-c261-11eb-9f5f-a127439c92d4.png)
![изображение](https://user-images.githubusercontent.com/37917037/120234728-3dd64180-c261-11eb-8318-b7caf59a17d9.png)

Ты чего )

2021-05-31 19:49 UTC, wrgraff commented on index.html
> +    <section class="promo1">
Про все эти 1-2-3 уже писал выше.
А главное: в чем смысл то, не пойму. Слайды одинаковые

2021-05-31 19:49 UTC, wrgraff commented on index.html
> +      <a class="btn" href="catalog.html">Подробнее</a>
Вот тут я еще понимаю `btn`.
И таких кнопок с желтой полосой на проекте не одна. Вот их и надо объединить под этим классом

2021-05-31 19:49 UTC, wrgraff commented on index.html
> +        <dd class="characteristics-item">Дальность полета</dd>
И то и другое айтем? Точно?

2021-05-31 19:49 UTC, wrgraff commented on index.html
> +      <li class="btn">
Тут вообще на списке класс...

2021-05-31 19:49 UTC, wrgraff commented on index.html
> +    <section class="conditions2">
Какой еще `conditions2`?
Не, у каждой сущности надо найти уникальное имя

2021-05-31 19:49 UTC, wrgraff commented on index.html
> +        <p class="conditions2-p">Мы с удовольствием доставим ваш товар прямо к вашему
Скорее это текст, а вся секция какой-нибудь контент

2021-05-31 19:49 UTC, wrgraff commented on index.html
> +      <p class="about_us-p">Мы можем доставить ваш товар в самые отдаленные точки
`p` означает параграф что ли?
Зачем нам в классе название тега

2021-05-31 19:49 UTC, wrgraff commented on index.html
> +      <textarea class="userMessage" name="user-message" id="user-message" placeholder="В свободной форме"></textarea>
Опять стиль нейминга сменился на лету. Так нельзя

2021-05-31 19:49 UTC, wrgraff commented on index.html
> +  <section class="modal-form">
А может быть такое, что все-таки модалка — это один и тот же элемент?
А уж внутри он различается содержанием

2021-06-10 16:30 UTC, wrgraff approved these changes

2021-06-10 16:30 UTC, merged